#!/usr/bin/env bash
# compose/backup/entrypoint.sh — with arguments: run them (one-shots such as `compose run --rm backup
# /opt/backup/backup.sh --kind manual`). Without: render the crontab and run supercronic in the foreground.
#   BACKUP_SCHEDULE        nightly backup            (default "0 2 * * *", in TZ)
#   RESTORE_TEST_SCHEDULE  weekly restore test       (default "0 3 * * 0")
# When BACKUP_ENABLED is not "true" or BACKUP_REMOTES is empty, no job is scheduled (a heartbeat keeps the service
# healthy) and the reason is logged — `make doctor` reports the same thing.
# shellcheck disable=SC2310,SC2311,SC2312
set -euo pipefail
# shellcheck source=lib.sh
source /opt/backup/lib.sh

if (( $# > 0 )); then
  exec "${@}"
fi

crontab=/tmp/crontab
{
  printf '# generated by /opt/backup/entrypoint.sh at container start (TZ=%s)\n' "${TZ:-UTC}"
  if [[ "${BACKUP_ENABLED:-false}" == "true" && -n "${BACKUP_REMOTES:-}" ]]; then
    printf '%s /opt/backup/backup.sh --kind daily\n' "${BACKUP_SCHEDULE:-0 2 * * *}"
    printf '%s /opt/backup/restore-test.sh\n' "${RESTORE_TEST_SCHEDULE:-0 3 * * 0}"
  else
    printf '@hourly true\n'
  fi
} >"${crontab}"

if [[ "${BACKUP_ENABLED:-false}" != "true" ]]; then
  warn "BACKUP_ENABLED is not true — no backups are scheduled (make backup-now still works)"
elif [[ -z "${BACKUP_REMOTES:-}" ]]; then
  warn "BACKUP_REMOTES is empty — no backups are scheduled; set e.g. BACKUP_REMOTES=\"r2:n8n-backups/prod\" in .env"
else
  info "scheduled: backup '${BACKUP_SCHEDULE:-0 2 * * *}', restore test '${RESTORE_TEST_SCHEDULE:-0 3 * * 0}' (TZ=${TZ:-UTC}) -> ${BACKUP_REMOTES}"
fi
mkdir -p "${STATE_DIR}"
exec supercronic -passthrough-logs "${crontab}"
