#!/usr/bin/env bash
# compose/backup/entrypoint.sh — with arguments: run them (one-shots such as `compose run --rm backup
# /opt/backup/backup.sh --kind manual`). Without: render the crontab and run supercronic in the foreground.
#   BACKUP_SCHEDULE        nightly backup            (default "0 2 * * *", in TZ)
#   RESTORE_TEST_SCHEDULE  weekly restore test       (default "0 3 * * 0")
#   cert-check             hourly at :17, always   (cert_expiry_timestamp_seconds for the monitoring profile)
# When BACKUP_ENABLED is not "true" or BACKUP_REMOTES is empty, no backup job is scheduled and the reason is logged —
# `make doctor` reports the same thing.
# shellcheck disable=SC2310,SC2311,SC2312
set -euo pipefail
# shellcheck source=lib.sh
source /opt/backup/lib.sh

if (( $# > 0 )); then
  exec "${@}"
fi

scheduled=0
if [[ "${BACKUP_ENABLED:-false}" == "true" && -n "${BACKUP_REMOTES:-}" ]]; then
  scheduled=1
fi

# Scheduler metrics for the BackupMissing / RestoreTestStale alerts: whether backups are scheduled, and since when (the
# 26 h / 8 day clocks start then — not at the epoch on a fresh install, and they stop while backups are switched off).
# The "since" time survives restarts and is reset whenever the schedule goes from off (or unknown) to on.
mkdir -p "${STATE_DIR}/metrics.d"
since_file="${STATE_DIR}/backup-schedule-since"
if (( scheduled )); then
  if [[ ! -s "${since_file}" ]] || [[ "$(cut -d' ' -f1 "${since_file}")" != "1" ]]; then
    printf '1 %s\n' "$(date +%s)" >"${since_file}"
  fi
else
  printf '0 %s\n' "$(date +%s)" >"${since_file}"
fi
{
  printf '# HELP backup_schedule_enabled 1 when the nightly backup and the weekly restore test are scheduled\n'
  printf '# TYPE backup_schedule_enabled gauge\n'
  printf 'backup_schedule_enabled %s\n' "${scheduled}"
  printf 'backup_schedule_enabled_since_timestamp_seconds %s\n' "$(cut -d' ' -f2 "${since_file}")"
} | write_metrics scheduler

crontab=/tmp/crontab
{
  printf '# generated by /opt/backup/entrypoint.sh at container start (TZ=%s)\n' "${TZ:-UTC}"
  if (( scheduled )); then
    printf '%s /opt/backup/backup.sh --kind daily\n' "${BACKUP_SCHEDULE:-0 2 * * *}"
    printf '%s /opt/backup/restore-test.sh\n' "${RESTORE_TEST_SCHEDULE:-0 3 * * 0}"
  fi
  # certificate expiry for the monitoring profile's CertExpiring alert (cheap; independent of BACKUP_ENABLED)
  printf '17 * * * * /opt/backup/cert-check.sh\n'
} >"${crontab}"

if [[ "${BACKUP_ENABLED:-false}" != "true" ]]; then
  warn "BACKUP_ENABLED is not true — no backups are scheduled (make backup-now still works)"
elif [[ -z "${BACKUP_REMOTES:-}" ]]; then
  warn "BACKUP_REMOTES is empty — no backups are scheduled; set e.g. BACKUP_REMOTES=\"r2:n8n-backups/prod\" in .env"
else
  info "scheduled: backup '${BACKUP_SCHEDULE:-0 2 * * *}', restore test '${RESTORE_TEST_SCHEDULE:-0 3 * * 0}' (TZ=${TZ:-UTC}) -> ${BACKUP_REMOTES}"
fi
exec supercronic -passthrough-logs "${crontab}"
